# Generated by Django 4.0 on 2024-03-18 06:55

from django.db import migrations, models
import django.db.models.deletion
import yonfen.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(error_messages={'unique': '이미 등록된 이름입니다'}, max_length=10, validators=[yonfen.validators.validate_no_special_characters])),
                ('user_pic', models.ImageField(default='default_profile_pic.jpg', upload_to='user_pics')),
                ('student_number', models.CharField(error_messages={'unique': '이미 등록된 학번입니다'}, max_length=10, null=True, unique=True, validators=[yonfen.validators.validate_no_special_characters])),
                ('major', models.CharField(max_length=20, validators=[yonfen.validators.validate_no_special_characters])),
                ('join_year', models.CharField(choices=[('1987-1', '1987-1'), ('1987-2', '1987-2'), ('1988-1', '1988-1'), ('1988-2', '1988-2'), ('1989-1', '1989-1'), ('1989-2', '1989-2'), ('1990-1', '1990-1'), ('1990-2', '1990-2'), ('1991-1', '1991-1'), ('1991-2', '1991-2'), ('1992-1', '1992-1'), ('1992-2', '1992-2'), ('1993-1', '1993-1'), ('1993-2', '1993-2'), ('1994-1', '1994-1'), ('1994-2', '1994-2'), ('1995-1', '1995-1'), ('1995-2', '1995-2'), ('1996-1', '1996-1'), ('1996-2', '1996-2'), ('1997-1', '1997-1'), ('1997-2', '1997-2'), ('1998-1', '1998-1'), ('1998-2', '1998-2'), ('1999-1', '1999-1'), ('1999-2', '1999-2'), ('2000-1', '2000-1'), ('2000-2', '2000-2'), ('2001-1', '2001-1'), ('2001-2', '2001-2'), ('2002-1', '2002-1'), ('2002-2', '2002-2'), ('2003-1', '2003-1'), ('2003-2', '2003-2'), ('2004-1', '2004-1'), ('2004-2', '2004-2'), ('2005-1', '2005-1'), ('2005-2', '2005-2'), ('2006-1', '2006-1'), ('2006-2', '2006-2'), ('2007-1', '2007-1'), ('2007-2', '2007-2'), ('2008-1', '2008-1'), ('2008-2', '2008-2'), ('2009-1', '2009-1'), ('2009-2', '2009-2'), ('2010-1', '2010-1'), ('2010-2', '2010-2'), ('2011-1', '2011-1'), ('2011-2', '2011-2'), ('2012-1', '2012-1'), ('2012-2', '2012-2'), ('2013-1', '2013-1'), ('2013-2', '2013-2'), ('2014-1', '2014-1'), ('2014-2', '2014-2'), ('2015-1', '2015-1'), ('2015-2', '2015-2'), ('2016-1', '2016-1'), ('2016-2', '2016-2'), ('2017-1', '2017-1'), ('2017-2', '2017-2'), ('2018-1', '2018-1'), ('2018-2', '2018-2'), ('2019-1', '2019-1'), ('2019-2', '2019-2'), ('2020-1', '2020-1'), ('2020-2', '2020-2'), ('2021-1', '2021-1'), ('2021-2', '2021-2'), ('2022-1', '2022-1'), ('2022-2', '2022-2'), ('2023-1', '2023-1'), ('2023-2', '2023-2')], default='2020-1', max_length=7)),
            ],
        ),
    ]
