# Generated by Django 4.0 on 2024-03-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonfen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email'),
        ),
    ]
