# Generated by Django 4.0 on 2024-03-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('yonfen', '0002_alter_profile_join_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image1', models.ImageField(blank=True, upload_to='post_pics')),
                ('image2', models.ImageField(blank=True, upload_to='post_pics')),
                ('image3', models.ImageField(blank=True, upload_to='post_pics')),
                ('image4', models.ImageField(blank=True, upload_to='post_pics')),
                ('image5', models.ImageField(blank=True, upload_to='post_pics')),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='auth.user')),
            ],
            options={
                'ordering': ['-dt_created'],
            },
        ),
    ]
