# Generated by Django 4.0 on 2024-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonfen', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(error_messages={'unique': '이미 등록된 학번입니다'}, max_length=14, null=True, unique=True),
        ),
    ]
