# Generated by Django 4.0.1 on 2024-06-23 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yonfen.models
import yonfen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yonfen', '0004_alter_post_author_comment_attandance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('major', models.CharField(max_length=20, validators=[yonfen.validators.validate_no_special_characters])),
                ('join_year', models.CharField(choices=[('1987-1', '1987-1'), ('1987-2', '1987-2'), ('1988-1', '1988-1'), ('1988-2', '1988-2'), ('1989-1', '1989-1'), ('1989-2', '1989-2'), ('1990-1', '1990-1'), ('1990-2', '1990-2'), ('1991-1', '1991-1'), ('1991-2', '1991-2'), ('1992-1', '1992-1'), ('1992-2', '1992-2'), ('1993-1', '1993-1'), ('1993-2', '1993-2'), ('1994-1', '1994-1'), ('1994-2', '1994-2'), ('1995-1', '1995-1'), ('1995-2', '1995-2'), ('1996-1', '1996-1'), ('1996-2', '1996-2'), ('1997-1', '1997-1'), ('1997-2', '1997-2'), ('1998-1', '1998-1'), ('1998-2', '1998-2'), ('1999-1', '1999-1'), ('1999-2', '1999-2'), ('2000-1', '2000-1'), ('2000-2', '2000-2'), ('2001-1', '2001-1'), ('2001-2', '2001-2'), ('2002-1', '2002-1'), ('2002-2', '2002-2'), ('2003-1', '2003-1'), ('2003-2', '2003-2'), ('2004-1', '2004-1'), ('2004-2', '2004-2'), ('2005-1', '2005-1'), ('2005-2', '2005-2'), ('2006-1', '2006-1'), ('2006-2', '2006-2'), ('2007-1', '2007-1'), ('2007-2', '2007-2'), ('2008-1', '2008-1'), ('2008-2', '2008-2'), ('2009-1', '2009-1'), ('2009-2', '2009-2'), ('2010-1', '2010-1'), ('2010-2', '2010-2'), ('2011-1', '2011-1'), ('2011-2', '2011-2'), ('2012-1', '2012-1'), ('2012-2', '2012-2'), ('2013-1', '2013-1'), ('2013-2', '2013-2'), ('2014-1', '2014-1'), ('2014-2', '2014-2'), ('2015-1', '2015-1'), ('2015-2', '2015-2'), ('2016-1', '2016-1'), ('2016-2', '2016-2'), ('2017-1', '2017-1'), ('2017-2', '2017-2'), ('2018-1', '2018-1'), ('2018-2', '2018-2'), ('2019-1', '2019-1'), ('2019-2', '2019-2'), ('2020-1', '2020-1'), ('2020-2', '2020-2'), ('2021-1', '2021-1'), ('2021-2', '2021-2'), ('2022-1', '2022-1'), ('2022-2', '2022-2'), ('2023-1', '2023-1'), ('2023-2', '2023-2'), ('2024-1', '2024-1'), ('2024-2', '2024-2')], default='2020-1', max_length=7)),
                ('status', models.CharField(choices=[('졸업', '졸업'), ('재학', '재학'), ('휴학', '휴학')], max_length=10)),
                ('fencing', models.CharField(choices=[('플뢰레', '플뢰레'), ('에페', '에페'), ('사브르', '미정'), ('미정', '미정')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='attandance',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='join_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.AddField(
            model_name='attandance',
            name='check_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image3_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image4_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image5_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여자', '여자'), ('남자', '남자')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_pic',
            field=models.FileField(blank=True, upload_to=yonfen.models.profile_pic_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='user_pic_url',
            field=models.URLField(blank=True, default='https://yonfen.s3.amazonaws.com/default_profile_pic.jpg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.FileField(blank=True, upload_to=yonfen.models.post_pic_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.FileField(blank=True, upload_to=yonfen.models.post_pic_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.FileField(blank=True, upload_to=yonfen.models.post_pic_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.FileField(blank=True, upload_to=yonfen.models.post_pic_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.FileField(blank=True, upload_to=yonfen.models.post_pic_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(error_messages={'unique': '이미 등록된 학번입니다'}, max_length=14, unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
