# Generated by Django 4.0.1 on 2024-06-25 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yonfen', '0005_code_student_test_rename_user_attandance_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('rank_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.IntegerField(default=0)),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
                ('total_attendances', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.DeleteModel(
            name='Attandance',
        ),
        migrations.AddField(
            model_name='userattendance',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonfen.code'),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
